# Generated by Django 5.2.6 on 2025-09-30 23:58

import django.db.models.deletion
import warz.player.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1, verbose_name='level')),
                ('is_vip', models.BooleanField(default=False, verbose_name='is vip')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=warz.player.models.avatar_upload_to, verbose_name='avatar')),
                ('presentation', models.TextField(blank=True, null=True, verbose_name='presentation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
    ]
