# Generated by Django 5.2.6 on 2025-09-30 23:48

import warz.player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=warz.player.models.avatar_upload_to, verbose_name='avatar'),
        ),
    ]
