# Generated by Django 5.2.6 on 2025-12-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Barracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClayFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Granary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
                ('build_speed_factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
                ('base_population_capacity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='IronMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='LumberMill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quarry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Watchtower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('base_wood_cost', models.IntegerField(default=100)),
                ('base_stone_cost', models.IntegerField(default=100)),
                ('base_iron_cost', models.IntegerField(default=100)),
            ],
        ),
    ]
