# Generated by Django 5.2.6 on 2025-12-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='barracks',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='clayfarm',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='farm',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='granary',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='headquarters',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='housing',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='ironmine',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='lumbermill',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='market',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='quarry',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='stable',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='wall',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddField(
            model_name='watchtower',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.village'),
        ),
        migrations.AddConstraint(
            model_name='academy',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_academy_village'),
        ),
        migrations.AddConstraint(
            model_name='barracks',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_barracks_village'),
        ),
        migrations.AddConstraint(
            model_name='clayfarm',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_clayfarm_village'),
        ),
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_farm_village'),
        ),
        migrations.AddConstraint(
            model_name='granary',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_granary_village'),
        ),
        migrations.AddConstraint(
            model_name='headquarters',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_headquarters_village'),
        ),
        migrations.AddConstraint(
            model_name='housing',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_housing_village'),
        ),
        migrations.AddConstraint(
            model_name='ironmine',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_ironmine_village'),
        ),
        migrations.AddConstraint(
            model_name='lumbermill',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_lumbermill_village'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_market_village'),
        ),
        migrations.AddConstraint(
            model_name='quarry',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_quarry_village'),
        ),
        migrations.AddConstraint(
            model_name='stable',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_stable_village'),
        ),
        migrations.AddConstraint(
            model_name='wall',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_wall_village'),
        ),
        migrations.AddConstraint(
            model_name='watchtower',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_watchtower_village'),
        ),
    ]
